# Generated by Django 4.0.5 on 2022-06-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_alter_news_content_alter_news_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
