# Generated by Django 4.0.5 on 2022-06-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0005_remove_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
